apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvmpv-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: lvmpv-node
  template:
    metadata:
      labels:
        app: lvmpv-node
    spec:
      serviceAccountName: lvmpv-node
      hostPID: true
      containers:
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/lvmpv.yetanother.io/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: lvmpv-node
          image: lvmpv:latest
          imagePullPolicy: Never
          args:
            - --mode=node
            - --csi-endpoint=unix:///csi/csi.sock
            - --node-id=$(NODE_NAME)
            - --vg-name=VG01
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: dev
              mountPath: /dev
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lvmpv.yetanother.io
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: dev
          hostPath:
            path: /dev
